<<: !include ./includes/secrets.yaml
<<: !include ./includes/common.yaml

esphome:
  name: hot_tub
  on_boot:
    then:
      - output.turn_on: led_status

esp32:
  board: esp32dev
  framework:
    type: esp-idf

i2c:
  sda: GPIO4
  scl:
    number: GPIO15
    ignore_strapping_warning: true

one_wire:
  - platform: gpio
    pin: GPIO32

output:
  - platform: gpio
    pin: GPIO25
    id: led_status

pcf8574:
  - id: inputs
    address: 0x22
  - id: outputs
    address: 0x24

switch:
  - platform: gpio
    id: relay_filter_pump
    name: "Filter pump"
    icon: mdi:pump
    pin:
      pcf8574: outputs
      number: 1
      mode: OUTPUT
      inverted: true
  - platform: gpio
    id: relay_blower
    name: "Blower"
    icon: mdi:chart-bubble
    pin:
      pcf8574: outputs
      number: 2
      mode: OUTPUT
      inverted: true
    on_turn_on:
      - delay: 3min
      - switch.turn_off: relay_blower
  - platform: gpio
    id: relay_4
    name: "Flow alarm"
    icon: mdi:alarm-light
    pin:
      pcf8574: outputs
      number: 3
      mode: OUTPUT
      inverted: true
  - platform: gpio
    name: "LED strips"
    icon: mdi:led-strip
    pin:
      pcf8574: outputs
      number: 4
      mode: OUTPUT
      inverted: true
  - platform: gpio
    id: relay_lights
    name: "Lights"
    icon: mdi:wall-sconce-round-variant
    pin:
      pcf8574: outputs
      number: 5
      mode: OUTPUT
      inverted: true

binary_sensor:
  - platform: gpio
    name: "Filter pump button"
    pin:
      pcf8574: inputs
      number: 0
      mode: INPUT
      inverted: true
    filters:
      - delayed_on: 50ms
    on_press:
      - switch.toggle: relay_filter_pump
  - platform: gpio
    name: "Blower button"
    pin:
      pcf8574: inputs
      number: 1
      mode: INPUT
      inverted: true
    filters:
      - delayed_on: 50ms
    on_press:
      - switch.toggle: relay_blower
  - platform: gpio
    name: "Lights button"
    pin:
      pcf8574: inputs
      number: 2
      mode: INPUT
      inverted: true
    filters:
      - delayed_on: 50ms
    on_press:
      - switch.toggle: relay_lights
  - platform: gpio
    name: "Flow switch"
    pin:
      number: GPIO33
      mode: INPUT_PULLUP
      inverted: true

sensor:
  - platform: dallas_temp
    name: "Temperature"
    update_interval: 30s
