<<: !include ./includes/secrets.yaml
<<: !include ./includes/common.yaml

esphome:
  name: outside_hot_tub_light
  platform: ESP8266
  board: esp8285

output:
  - platform: gpio
    pin: GPIO12
    id: relay_1

light:
  - platform: binary
    name: "Outside | Hot tub light"
    id: light_1
    output: relay_1

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO0
      mode: INPUT_PULLUP
      inverted: true
    id: binary_sensor_1
    on_press:
      - light.toggle: light_1

status_led:
  pin:
    number: GPIO13
    inverted: yes
